// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckdkxzdtpstepefnopym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrZGt4emR0cHN0ZXBlZm5vcHltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MTk5ODAsImV4cCI6MjA3MTk5NTk4MH0.PknQcsyT8rmtPQFSIKJuy7uWQ_zdv60NwImOlo3aKOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});